[GLOBAL_PRAGMA]
grflangid = "0x66"
plural = "0"
gender = "m f n mp fp np"
case = "abl acc dat gen"

[STR_GRF_DESCRIPTION]
base = "Licentia: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Capacitates Vehicularum"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Exiguae"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Optimae"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Nimiae"

[STR_PARAM_ROSTER]
base = "Vehicula Adhibenda"

[STR_PARAM_ROSTER_DESC]
base = "Eligere vehicula adhibenda."

[STR_PARAM_ROSTER_OPTION_1]
base = "Erema"

[STR_NAME_SUFFIX_BOX_TRAM]
base = "Transviaria Raeda Clausa"

[STR_NAME_SUFFIX_BOX_TRUCK]
base = "Autoplaustrum Cubicum"

[STR_NAME_SUFFIX_BUS]
base = "Laophorium"

[STR_NAME_SUFFIX_COACH]
base = "Carruca"

[STR_NAME_SUFFIX_COVERED_HOPPER_TRAM]
base = "Transviaria Raeda Infundibularis Tecta"

[STR_NAME_SUFFIX_COVERED_HOPPER_TRUCK]
base = "Autoplaustrum Infundibulare Tectum"

[STR_NAME_SUFFIX_DUMP_TRAM]
base = "Transviaria Raeda Demissa"

[STR_NAME_SUFFIX_DUMP_TRUCK]
base = "Autoplaustrum Demissum"

[STR_NAME_SUFFIX_EDIBLES_TANKER_TRAM]
base = "Transviaria Raeda Cisternina Edulium"

[STR_NAME_SUFFIX_EDIBLES_TANKER_TRUCK]
base = "Autoplaustrum Cisterninum Edulium"

[STR_NAME_SUFFIX_FLATBED_TRAM]
base = "Transviaria Raeda Plana"

[STR_NAME_SUFFIX_FLATBED_TRUCK]
base = "Autoplaustrum Planum"

[STR_NAME_SUFFIX_INTERMODAL_HAULER]
base = "Autoplaustrum Intermodale"

[STR_NAME_SUFFIX_LIVESTOCK_TRAM]
base = "Transviaria Raeda Pecuaria"

[STR_NAME_SUFFIX_LIVESTOCK_TRUCK]
base = "Autoplaustrum Pecuarium"

[STR_NAME_SUFFIX_MINING_TRUCK]
base = "Autoplaustrum Fodinale"

[STR_NAME_SUFFIX_OPEN_TRAM]
base = "Transviaria Raeda Aperta"

[STR_NAME_SUFFIX_OPEN_TRUCK]
base = "Autoplaustrum Apertum"

[STR_NAME_SUFFIX_PASSENGER_TRAM]
base = "Transviaria Raeda Vectoria"

[STR_NAME_SUFFIX_REEFER_TRAM]
base = "Transviaria Raeda Frigidaria"

[STR_NAME_SUFFIX_REEFER_TRUCK]
base = "Autoplaustrum Frigidarium"

[STR_NAME_SUFFIX_SUPPLIES_TRAM]
base = "Transviaria Raeda Apparatuum"

[STR_NAME_SUFFIX_SUPPLIES_TRUCK]
base = "Autoplaustrum Apparatuum"

[STR_NAME_SUFFIX_TANKER_TRAM]
base = "Transviaria Raeda Cisternina"

[STR_NAME_SUFFIX_TANKER_TRUCK]
base = "Autoplaustrum Cisterninum"

[STR_COASTER]
base = "Bos Salivit Supra Lunam (memento adhuc progredi)"
