[GLOBAL_PRAGMA]
grflangid = "0x23"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "Lizenz: {SILVER}GPL v2{}{BLACK}"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY]
base = "Stroossegefierkapazitéit"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_0]
base = "Mickreg"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_1]
base = "Fantastesch"

[STR_PARAM_ADJUST_VEHICLE_CAPACITY_OPTION_2]
base = "Exzessiv"

[STR_PARAM_ROSTER]
base = "Lëscht"

[STR_PARAM_ROSTER_DESC]
base = "Wiel wellechen Set vu Gefierer benotzt soll ginn."

[STR_PARAM_ROSTER_OPTION_1]
base = "Ödland"

[STR_NAME_SUFFIX_BOX_TRAM]
base = "Këschten-Tram"

[STR_NAME_SUFFIX_BOX_TRUCK]
base = "Këschtecamion"

[STR_NAME_SUFFIX_BUS]
base = "Bus"

[STR_NAME_SUFFIX_COACH]
base = "Passagéierwon"

[STR_NAME_SUFFIX_COVERED_HOPPER_TRAM]
base = "Iwwerdeckte Kipp-Tram"

[STR_NAME_SUFFIX_COVERED_HOPPER_TRUCK]
base = "Iwwerdeckte Kippcamion"

[STR_NAME_SUFFIX_DUMP_TRAM]
base = "Kippwagon-Tram"

[STR_NAME_SUFFIX_DUMP_TRUCK]
base = "Kippcamion"

[STR_NAME_SUFFIX_EDIBLES_TANKER_TRAM]
base = "Liewensmëttel-Tanker-Tram"

[STR_NAME_SUFFIX_EDIBLES_TANKER_TRUCK]
base = "Liewensmëttel-Tankcamion"

[STR_NAME_SUFFIX_FLATBED_TRAM]
base = "Flachbett-Tram"

[STR_NAME_SUFFIX_FLATBED_TRUCK]
base = "Flachbettcamion"

[STR_NAME_SUFFIX_INTERMODAL_HAULER]
base = "Containercamion"

[STR_NAME_SUFFIX_LIVESTOCK_TRAM]
base = "Véitransport-Tram"

[STR_NAME_SUFFIX_LIVESTOCK_TRUCK]
base = "Véitransport-Camion"

[STR_NAME_SUFFIX_MINING_TRUCK]
base = "Minnecamion"

[STR_NAME_SUFFIX_OPEN_TRAM]
base = "Openen Tram"

[STR_NAME_SUFFIX_OPEN_TRUCK]
base = "Opene Camion"

[STR_NAME_SUFFIX_PASSENGER_TRAM]
base = "Passagéier-Tram"

[STR_NAME_SUFFIX_REEFER_TRAM]
base = "Killwueren-Tram"

[STR_NAME_SUFFIX_REEFER_TRUCK]
base = "Killcamion"

[STR_NAME_SUFFIX_SUPPLIES_TRAM]
base = "Ersatzdeeler-Tram"

[STR_NAME_SUFFIX_SUPPLIES_TRUCK]
base = "Ersatzdeelercamion"

[STR_NAME_SUFFIX_TANKER_TRAM]
base = "Tanker-Tram"

[STR_NAME_SUFFIX_TANKER_TRUCK]
base = "Tankcamion"

[STR_COASTER]
base = "Bliblablubb (e Reminder vum Andy...)"

[STR_DOGTRACK]
base = "Hënn si brong, munchmol."
